import React, { useState } from 'react';
import { KeyboardAvoidingView, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { useApp, User } from '../context/AppContext';
import { COLORS } from '../theme/colors';

type Props = { mode: 'login' | 'signup'; onChangeMode: () => void };
export function AuthScreen({ mode, onChangeMode }: Props) {
  const { login, signup } = useApp();
  const [form, setForm] = useState({ username: '', fullName: '', email: '', password: '', confirm: '' });
  const [showPassword, setShowPassword] = useState(false);
  const [error, setError] = useState('');
  const update = (key: keyof typeof form, value: string) => setForm(current => ({ ...current, [key]: value }));
  const submit = () => {
    if (mode === 'signup' && !form.username.trim()) return setError('Username is required.');
    if (mode === 'signup' && !form.fullName.trim()) return setError('Full name is required.');
    if (!form.email.trim() || !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(form.email)) return setError('Enter a valid email address.');
    if (!form.password) return setError('Password is required.');
    if (mode === 'signup' && form.password !== form.confirm) return setError('Passwords do not match.');
    const user: User = { username: form.username || form.email.split('@')[0], fullName: form.fullName || form.email.split('@')[0], email: form.email, phone: '' };
    (mode === 'login' ? login : signup)(user);
  };
  return <KeyboardAvoidingView style={styles.container} behavior={Platform.OS === 'ios' ? 'padding' : undefined}><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><Text style={styles.logo}>CarApp</Text><Text style={styles.kicker}>PREMIUM MOTORS</Text><Text style={styles.title}>{mode === 'login' ? 'Welcome back' : 'Create your account'}</Text><Text style={styles.subtitle}>{mode === 'login' ? 'Your next drive is waiting.' : 'Save favorites, compare cars, and book with ease.'}</Text>{mode === 'signup' && <><TextInput style={styles.input} placeholder="Username" placeholderTextColor={COLORS.muted} value={form.username} onChangeText={v => update('username', v)} /><TextInput style={styles.input} placeholder="Full name" placeholderTextColor={COLORS.muted} value={form.fullName} onChangeText={v => update('fullName', v)} /></>}<TextInput style={styles.input} placeholder="Email or Gmail" placeholderTextColor={COLORS.muted} keyboardType="email-address" autoCapitalize="none" value={form.email} onChangeText={v => update('email', v)} /><View style={styles.passwordWrap}><TextInput style={styles.password} placeholder="Password" placeholderTextColor={COLORS.muted} secureTextEntry={!showPassword} value={form.password} onChangeText={v => update('password', v)} /><Pressable onPress={() => setShowPassword(value => !value)}><Text style={styles.show}>{showPassword ? 'Hide' : 'Show'}</Text></Pressable></View>{mode === 'signup' && <TextInput style={styles.input} placeholder="Confirm password" placeholderTextColor={COLORS.muted} secureTextEntry value={form.confirm} onChangeText={v => update('confirm', v)} />}{!!error && <Text style={styles.error}>{error}</Text>}<Pressable style={styles.button} onPress={submit}><Text style={styles.buttonText}>{mode === 'login' ? 'Login' : 'Sign Up'}</Text></Pressable>{mode === 'login' && <Pressable onPress={() => setError('Password reset is not available in offline mode.')}><Text style={styles.link}>Forgot Password?</Text></Pressable>}<Pressable onPress={onChangeMode}><Text style={styles.switchText}>{mode === 'login' ? "Don't have an account? Sign Up" : 'Already have an account? Login'}</Text></Pressable></ScrollView></KeyboardAvoidingView>;
}
const styles = StyleSheet.create({ container: { flex: 1, backgroundColor: COLORS.background }, content: { flexGrow: 1, justifyContent: 'center', padding: 24 }, logo: { color: COLORS.text, fontSize: 42, fontWeight: '900' }, kicker: { color: COLORS.gold, fontSize: 11, fontWeight: '800', letterSpacing: 2, marginTop: 4 }, title: { color: COLORS.text, fontSize: 30, fontWeight: '800', marginTop: 54 }, subtitle: { color: COLORS.muted, fontSize: 16, marginTop: 8, marginBottom: 28 }, input: { backgroundColor: COLORS.input, color: COLORS.text, borderRadius: 14, borderWidth: 1, borderColor: COLORS.border, padding: 15, marginBottom: 12 }, passwordWrap: { flexDirection: 'row', alignItems: 'center', backgroundColor: COLORS.input, borderRadius: 14, borderWidth: 1, borderColor: COLORS.border, marginBottom: 12 }, password: { flex: 1, color: COLORS.text, padding: 15 }, show: { color: COLORS.gold, fontWeight: '800', paddingHorizontal: 14 }, error: { color: COLORS.error, marginBottom: 12 }, button: { backgroundColor: COLORS.gold, borderRadius: 14, padding: 16, alignItems: 'center', marginTop: 8 }, buttonText: { color: COLORS.background, fontWeight: '900', fontSize: 16 }, link: { color: COLORS.gold, textAlign: 'center', marginTop: 18, fontWeight: '700' }, switchText: { color: COLORS.muted, textAlign: 'center', marginTop: 30, fontWeight: '600' } });